language: c
script: 
  - cp privateContact.example.tex privateContact.tex
  - make resume.pdf
addons:
  artifacts:
    paths:
    - resume.pdf
deploy:
  provider: gcs
  access_key_id: GOOGICKK3EEDQ3YD43R3
  secret_access_key:
    secure: a09hnvM232c9pdpmzuKtIC7A4jIpe8pdpRvUu3jt3/1r97A7xTUrFYH9a16aB6d4oiW3ab39l8TwlkzqBoARMLA9QYLk3qt/WExwAOmqVjOWIJR/eF4ucH2JUAWJWcaXPFAmy95qWVna1c6cLSWA2yQSoIN/4U4LHc4X+xCboV5sllHu2mTLde8wqcpG4ZTySGIl09hl51I8haHnV8sk2XZhtcQXyI3X5PXjfZXJhpOYNwBAUvz6ayDX0n/DY1WGgsQZCjHqqiTHowg02nQSs7/6qQYDrK/mFhC7g8ZdpXnUr+37nTVbNWUM9AErHcx93haT7I/RF80sp4lX2rz1Rzld6003QBAXrUBHMM92kSZVCCn1KbTQPan+/CS1NQGYwRfc8UjvGxI0unlI8CPm6TCec1MIDm/tkrT/HwGJhN4jyPgXZbPfrlGnfSMnATuuHa/rXa71bKXEixvzJuXxh9eaGF+4W8wu9r6ObsBmraJ0YYt4sKJf38CtAU3O3PHDaGF27bd1GgHi/hLSaU7KgVYgAXuh1A4dNvx1MKmjE6elx6A77X8/688EVAENjOqM47IDZFY4WVYsNHHcwHr3KpxoShwUPSiY9B+nleNyXVBZzzeu8G5hGMaYgF+P1bAMHlIOzmvTx3FloeaYqf5PIcdSuLZXglAqLop7izthZ50=
  bucket: public-resume
  acl: public-read
