name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apt-get install texlive-full
    - name: Create fake private contact file
      run: cp privateContact.example.tex privateContact.tex
    - name: Compile resume LaTeX
      run: make resume.pdf
